#
# ███╗░░██╗███████╗██╗░░░██╗██╗░░░░░░█████╗░███╗░░██╗██████╗░██╗░█████╗░████████╗░█████╗░░█████╗░██╗░░░░░░██████╗
# ████╗░██║██╔════╝╚██╗░██╔╝██║░░░░░██╔══██╗████╗░██║██╔══██╗██║██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗██║░░░░░██╔════╝
# ██╔██╗██║█████╗░░░╚████╔╝░██║░░░░░███████║██╔██╗██║██║░░██║██║███████║░░░██║░░░██║░░██║██║░░██║██║░░░░░╚█████╗░
# ██║╚████║██╔══╝░░░░╚██╔╝░░██║░░░░░██╔══██║██║╚████║██║░░██║██║██╔══██║░░░██║░░░██║░░██║██║░░██║██║░░░░░░╚═══██╗
# ██║░╚███║███████╗░░░██║░░░███████╗██║░░██║██║░╚███║██████╔╝██║██║░░██║░░░██║░░░╚█████╔╝╚█████╔╝███████╗██████╔╝
# ╚═╝░░╚══╝╚══════╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝╚═╝░░╚═╝░░░╚═╝░░░░╚════╝░░╚════╝░╚══════╝╚═════╝░
# Version 1.14.1
# Contactez-moi sur Discord en cas de bugs !
# --> @Yende

Messages :
  News : "Nouveau plugin sur le serveur ! NeylandiaTools contiendra à terme une série de commandes pour vous simplifier la vie sur Neylandia. Vous pouvez faire /help NeylandiaTools pour consulter la liste des commandes."
  Auto-message : true